# python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 9 --sample_ratio 0.00 --sketch_type 2
# python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 9 --sample_ratio 0.01 --sketch_type 2
# python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 9 --sample_ratio 0.1 --sketch_type 2
# python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 9 --sample_ratio 0.25 --sketch_type 2
# python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 9 --sample_ratio 0.5 --sketch_type 2
# python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 9 --sample_ratio 1.00 --sketch_type 2


python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 9 --sample_ratio 1.00 --sketch_type 2
python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 9 --sample_ratio 0.5 --sketch_type 2
python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 9 --sample_ratio 0.25 --sketch_type 2
python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 0 --sample_ratio 0.10 --sketch_type 2
python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 1 --sample_ratio 0.05 --sketch_type 2
python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 2 --sample_ratio 0.03 --sketch_type 2
python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 3 --sample_ratio 0.01 --sketch_type 2
python3 main.py --config configs/scribble_proposed_illust_200epoch.yaml --resume_model results/dataset_name/BrownianBridge_scribble_illust/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 4 --sample_ratio 0.00 --sketch_type 2
