# python3 main.py --config configs/scribble_proposed_real_200epoch_rev.yaml --resume_model results/dataset_name/BrownianBridge_scribble_real_rev_200k/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 3 --sample_ratio 0.25 --sketch_type 0
# python3 main.py --config configs/scribble_proposed_real_200epoch_rev.yaml --resume_model results/dataset_name/BrownianBridge_scribble_real_rev_200k/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 3 --sample_ratio 0.25 --sketch_type 1
# python3 main.py --config configs/scribble_proposed_real_200epoch_rev.yaml --resume_model results/dataset_name/BrownianBridge_scribble_real_rev_200k/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 3 --sample_ratio 0.25 --sketch_type 2
python3 main.py --config configs/scribble_proposed_real_200epoch_rev.yaml --resume_model results/dataset_name/BrownianBridge_scribble_real_rev_200k/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 5 --sample_ratio 0.25 --sketch_type 0
python3 main.py --config configs/scribble_proposed_real_200epoch_rev.yaml --resume_model results/dataset_name/BrownianBridge_scribble_real_rev_200k/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 5 --sample_ratio 0.25 --sketch_type 1
python3 main.py --config configs/scribble_proposed_real_200epoch_rev.yaml --resume_model results/dataset_name/BrownianBridge_scribble_real_rev_200k/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 5 --sample_ratio 0.25 --sketch_type 2
python3 main.py --config configs/dot_proposed_real_200epoch_rev.yaml --resume_model results/dataset_name/BBDM_dot_real/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 5 --sample_ratio 0.25 --sketch_type 0
python3 main.py --config configs/dot_proposed_real_200epoch_rev.yaml --resume_model results/dataset_name/BBDM_dot_real/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 5 --sample_ratio 0.25 --sketch_type 1
python3 main.py --config configs/dot_proposed_real_200epoch_rev.yaml --resume_model results/dataset_name/BBDM_dot_real/checkpoint/latest_model_200.pth --sample_to_eval --save_top --gpu_ids 5 --sample_ratio 0.25 --sketch_type 2
